# Generated by Django 4.2.30 on 2026-05-27 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_comment_id', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('author_channel_url', models.URLField(blank=True, default='', max_length=1024)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=1024)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at_source', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('toxicity_label', models.CharField(blank=True, choices=[('toxic', 'Toxic'), ('non_toxic', 'Non-Toxic')], help_text='Overall comment toxicity label', max_length=20, null=True)),
                ('toxicity_confidence', models.FloatField(blank=True, help_text='Confidence score from the model (0.0 - 1.0)', null=True)),
                ('annotation_source', models.CharField(blank=True, choices=[('auto', 'Automatic (AI)'), ('manual', 'Manual'), ('mixed', 'Mixed (AI + Manual)')], max_length=20, null=True)),
                ('model_response', models.JSONField(blank=True, help_text='Raw model response for debugging', null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('annotated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(db_index=True, max_length=100)),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('channel', models.CharField(blank=True, default='', max_length=255)),
                ('thumbnail', models.URLField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching Comments'), ('completed', 'Comments Fetched'), ('annotating', 'Annotating'), ('annotated', 'Fully Annotated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('comment_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtubelinks', to='comments.project')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('position', models.IntegerField(help_text='Position of the token in the comment')),
                ('start_offset', models.IntegerField(help_text='Start character offset in the original text')),
                ('end_offset', models.IntegerField(help_text='End character offset in the original text')),
                ('is_toxic', models.BooleanField(default=False, help_text='Whether this token is annotated as toxic')),
                ('toxicity_score', models.FloatField(blank=True, help_text='Toxicity score for this specific token (0.0 - 1.0)', null=True)),
                ('annotated_at', models.DateTimeField(blank=True, null=True)),
                ('annotation_source', models.CharField(choices=[('auto', 'Automatic (AI)'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='comments.comment')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('fetching', 'Fetching Comments'), ('annotating', 'Annotating Comments')], max_length=20)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_step', models.TextField(blank=True, default='')),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('youtube_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progresses', to='comments.youtubelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('json_sentence', 'JSON - Sentence Level'), ('json_token', 'JSON - Token Level'), ('json_llm', 'JSON - LLM Training'), ('xml_conll', 'XML - CoNLL Format'), ('csv_sentence', 'CSV - Sentence Level'), ('csv_token', 'CSV - Token Level')], max_length=30)),
                ('filter_toxicity', models.CharField(choices=[('all', 'All Comments'), ('toxic', 'Toxic Only'), ('non_toxic', 'Non-Toxic Only')], default='all', max_length=20)),
                ('comment_count', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(default=0)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='comments.project')),
                ('youtube_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='comments.youtubelink')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='youtube_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.youtubelink'),
        ),
        migrations.AddIndex(
            model_name='youtubelink',
            index=models.Index(fields=['project', 'status'], name='comments_yo_project_d87e75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='youtubelink',
            unique_together={('project', 'video_id')},
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['comment', 'position'], name='comments_to_comment_51af1c_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['comment', 'is_toxic'], name='comments_to_comment_8e84f7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskprogress',
            index=models.Index(fields=['youtube_link', 'status'], name='comments_ta_youtube_e85500_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['youtube_link', 'toxicity_label'], name='comments_co_youtube_d553de_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['youtube_link', 'youtube_comment_id'], name='comments_co_youtube_631317_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('youtube_link', 'youtube_comment_id')},
        ),
    ]
