# Generated by Django 4.2.30 on 2026-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='original_text',
            field=models.TextField(blank=True, default='', help_text='Original comment text if it was translated (non-Vietnamese)'),
        ),
    ]
