# Generated by Django 4.2.30 on 2026-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_is_meaningful'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelink',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtubelink',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
