# Generated by Django 4.2.30 on 2026-06-03 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0007_add_project_owner_and_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_api_key', models.CharField(blank=True, default='', help_text='YouTube Data API v3 key for fetching comments', max_length=500)),
                ('ollama_base_url', models.CharField(blank=True, default='', help_text='Ollama API base URL (e.g., http://localhost:11434)', max_length=500)),
                ('ollama_api_key', models.CharField(blank=True, default='', help_text='Ollama API authentication key', max_length=500)),
                ('ollama_model', models.CharField(blank=True, default='', help_text='Ollama model name (e.g., llama3, qwen3.6:27b)', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='token',
            name='comments_to_comment_8e84f7_idx',
        ),
        migrations.RemoveField(
            model_name='token',
            name='is_toxic',
        ),
        migrations.AlterField(
            model_name='comment',
            name='toxicity_label',
            field=models.CharField(blank=True, choices=[('toxic', 'Toxic'), ('non_toxic', 'Non-Toxic')], help_text='Overall comment toxicity label (legacy)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectlabels', to='comments.label'),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectlabels', to='comments.project'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(help_text='User who owns these settings', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
