# Generated by Django 4.2.30 on 2026-06-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_alter_label_owner_emailverification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_youtube_d553de_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='toxicity_label',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['youtube_link', 'ai_label'], name='comments_co_youtube_554561_idx'),
        ),
    ]
