# Generated by Django 4.2.30 on 2026-08-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_remove_comment_comments_co_youtube_d553de_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
