# Generated by Django 4.2.30 on 2026-09-03 08:10

import comments.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0013_project_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Chưa làm'), ('done', 'Đã gán nhãn'), ('skipped', 'Bỏ qua')], db_index=True, default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_position', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('comment_label', 'Gán nhãn câu'), ('token_label', 'Gán nhãn token'), ('adjudicate', 'Phân xử'), ('ai_annotate', 'AI gán nhãn'), ('reset', 'Xoá nhãn hàng loạt'), ('skip', 'Đánh dấu không có nghĩa')], max_length=30)),
                ('old_value', models.CharField(blank=True, default='', max_length=200)),
                ('new_value', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Người gán nhãn'), ('adjudicated', 'Phân xử bởi chủ dự án')], default='manual', max_length=20)),
                ('is_meaningful', models.BooleanField(blank=True, default=None, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Ghi chú của annotator')),
                ('time_spent_ms', models.PositiveIntegerField(default=0, help_text='Thời gian gán nhãn (ms) — dùng đo năng suất')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='Ví dụ: v1.0, 2026-09-03', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('export_format', models.CharField(default='json_token', max_length=30)),
                ('status', models.CharField(choices=[('building', 'Đang tạo'), ('ready', 'Sẵn sàng'), ('failed', 'Thất bại')], default='building', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('comment_count', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(default=0)),
                ('annotator_count', models.IntegerField(default=0)),
                ('agreement_score', models.FloatField(blank=True, help_text="Krippendorff's alpha tại thời điểm chốt phiên bản", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Người gán nhãn'), ('adjudicated', 'Phân xử bởi chủ dự án')], default='manual', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_processed',
            field=models.BooleanField(db_index=True, default=False, help_text='AI đã xử lý comment này (kể cả khi kết luận là nhãn O)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='gold_label',
            field=models.ForeignKey(blank=True, help_text='Nhãn chốt cuối cùng sau khi phân xử', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_gold_labeled', to='comments.projectlabel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='manual_annotation_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Số annotator đã gán nhãn comment này'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Chưa đủ annotator'), ('agreed', 'Đồng thuận'), ('conflict', 'Bất đồng — cần phân xử'), ('adjudicated', 'Đã phân xử')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='source_text',
            field=models.TextField(blank=True, default='', help_text='Văn bản gốc từ nguồn dữ liệu — bất biến, không bao giờ ghi đè'),
        ),
        migrations.AddField(
            model_name='project',
            name='annotators_per_comment',
            field=models.PositiveSmallIntegerField(default=1, help_text='Số annotator cần gán nhãn mỗi comment trước khi chốt nhãn vàng'),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_adjudicate',
            field=models.BooleanField(default=True, help_text='Tự động chốt nhãn vàng khi các annotator đồng thuận tuyệt đối'),
        ),
        migrations.AddField(
            model_name='project',
            name='guideline',
            field=models.TextField(blank=True, default='', help_text='Hướng dẫn gán nhãn hiển thị cho annotator (hỗ trợ xuống dòng)'),
        ),
        migrations.AddField(
            model_name='token',
            name='gold_label',
            field=models.ForeignKey(blank=True, help_text='Nhãn chốt cuối cùng sau khi phân xử', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_gold_labeled', to='comments.projectlabel'),
        ),
        migrations.AddField(
            model_name='youtubelink',
            name='kind',
            field=models.CharField(choices=[('youtube', 'YouTube video'), ('csv', 'CSV import'), ('manual', 'Nhập thủ công')], db_index=True, default='youtube', help_text='Loại nguồn dữ liệu', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='ollama_api_key',
            field=comments.fields.EncryptedCharField(blank=True, default='', help_text='Ollama API authentication key', max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='youtube_api_key',
            field=comments.fields.EncryptedCharField(blank=True, default='', help_text='YouTube Data API v3 key for fetching comments', max_length=500),
        ),
        migrations.AlterField(
            model_name='youtubelink',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['youtube_link', 'manual_label'], name='comments_co_youtube_91f077_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['youtube_link', 'is_meaningful'], name='comments_co_youtube_f1eaac_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['youtube_link', 'ai_processed'], name='comments_co_youtube_95225d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['youtube_link', 'review_status'], name='comments_co_youtube_61de2f_idx'),
        ),
        migrations.AddField(
            model_name='tokenannotation',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenannotation',
            name='project_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_annotations', to='comments.projectlabel'),
        ),
        migrations.AddField(
            model_name='tokenannotation',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='comments.token'),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_versions', to='comments.project'),
        ),
        migrations.AddField(
            model_name='commentannotation',
            name='annotator',
            field=models.ForeignKey(blank=True, help_text='NULL nghĩa là do AI gán', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentannotation',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='commentannotation',
            name='project_label',
            field=models.ForeignKey(blank=True, help_text='NULL nghĩa là annotator chọn "không nhãn" (tương đương O)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_annotations', to='comments.projectlabel'),
        ),
        migrations.AddField(
            model_name='annotationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotationevent',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='annotationevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_events', to='comments.project'),
        ),
        migrations.AddField(
            model_name='annotationassignment',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotationassignment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='annotationassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='comments.project'),
        ),
        migrations.AddIndex(
            model_name='tokenannotation',
            index=models.Index(fields=['token', 'source'], name='comments_to_token_i_35c521_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenannotation',
            index=models.Index(fields=['annotator', 'created_at'], name='comments_to_annotat_f1ca6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tokenannotation',
            constraint=models.UniqueConstraint(fields=('token', 'annotator', 'source'), name='uniq_token_annotation_per_annotator'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uniq_dataset_version_per_project'),
        ),
        migrations.AddIndex(
            model_name='commentannotation',
            index=models.Index(fields=['comment', 'source'], name='comments_co_comment_359799_idx'),
        ),
        migrations.AddIndex(
            model_name='commentannotation',
            index=models.Index(fields=['annotator', 'created_at'], name='comments_co_annotat_d6324f_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentannotation',
            constraint=models.UniqueConstraint(fields=('comment', 'annotator', 'source'), name='uniq_comment_annotation_per_annotator'),
        ),
        migrations.AddIndex(
            model_name='annotationevent',
            index=models.Index(fields=['project', '-created_at'], name='comments_an_project_e281db_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationevent',
            index=models.Index(fields=['comment', '-created_at'], name='comments_an_comment_78b47b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationevent',
            index=models.Index(fields=['actor', '-created_at'], name='comments_an_actor_i_f2ce06_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationassignment',
            index=models.Index(fields=['annotator', 'status'], name='comments_an_annotat_17d6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationassignment',
            index=models.Index(fields=['project', 'status'], name='comments_an_project_153566_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotationassignment',
            constraint=models.UniqueConstraint(fields=('comment', 'annotator'), name='uniq_assignment_per_annotator'),
        ),
    ]
