# Generated by Django 4.2.30 on 2026-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_backfill_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='span_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Các token cùng một cụm chia sẻ chung giá trị này', null=True),
        ),
    ]
