# Generated by Django 4.2.30 on 2026-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_backfill_span_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrecord',
            name='export_format',
            field=models.CharField(choices=[('conll', 'CoNLL-2003 (token + BIO)'), ('conll_full', 'CoNLL extended (with offsets)'), ('hf_jsonl', 'HuggingFace datasets JSONL'), ('spacy_json', 'spaCy training JSON'), ('doccano_jsonl', 'Doccano JSONL'), ('label_studio_json', 'Label Studio JSON'), ('json_sentence', 'JSON - sentence level'), ('json_token', 'JSON - token level'), ('jsonl', 'JSONL - token level'), ('xml', 'XML - full structure'), ('csv_sentence', 'CSV - sentence level'), ('csv_token', 'CSV - token level'), ('csv_spans', 'CSV - labelled spans only'), ('csv_annotations', 'CSV - per annotation'), ('xlsx', 'Excel workbook'), ('json_llm', 'JSONL - LLM fine-tuning'), ('xml_conll', 'XML (legacy name)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exportrecord',
            name='filter_toxicity',
            field=models.CharField(blank=True, default='all', help_text="'all' hoặc tên nhãn được dùng để lọc", max_length=100),
        ),
    ]
