# Generated by Django 4.2.30 on 2026-09-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_alter_exportrecord_export_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='snapshot_path',
            field=models.CharField(blank=True, default='', help_text='Ảnh chụp nhãn ở dạng chuẩn, dùng để phục hồi dự án về phiên bản này. Khác file_path: file_path là bản xuất cho người dùng cuối, có định dạng do người tạo chọn.', max_length=500),
        ),
    ]
