# Generated by Django 4.2.30 on 2026-09-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_datasetversion_snapshot_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationevent',
            name='action',
            field=models.CharField(choices=[('comment_label', 'Gán nhãn câu'), ('token_label', 'Gán nhãn token'), ('adjudicate', 'Phân xử'), ('ai_annotate', 'AI gán nhãn'), ('accept_ai', 'Chấp nhận đề xuất của AI'), ('reset', 'Xoá nhãn hàng loạt'), ('skip', 'Đánh dấu không có nghĩa')], max_length=30),
        ),
    ]
