# Generated by Django 4.2.30 on 2026-09-09 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0020_alter_annotationevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='current_step',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='current_step',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='file_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='review_filter',
            field=models.CharField(blank=True, default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('running', 'Đang xuất'), ('ready', 'Sẵn sàng tải'), ('failed', 'Thất bại')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='task_type',
            field=models.CharField(choices=[('fetching', 'Fetching Comments'), ('annotating', 'Annotating Comments'), ('importing', 'Importing CSV')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['project', 'status'], name='comments_ex_project_0da152_idx'),
        ),
    ]
