# Generated by Django 4.2.30 on 2026-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0022_clear_ai_span_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='step_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
